import type React from "react";

const styles: Record<string, React.CSSProperties> = {
  section: { marginBottom: 32 },
  headerRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    flexWrap: "wrap",
    gap: 8,
  },
  heading: { fontSize: 18, fontWeight: 600, color: "var(--text)" },
  count: { fontWeight: 400, color: "var(--text-muted)", fontSize: 14 },
  stats: { display: "flex", gap: 12, fontSize: 13 },
  statAligned: { color: "var(--success)" },
  statFailed: { color: "var(--warning)" },
  empty: {
    padding: "48px 24px",
    textAlign: "center",
    background: "var(--surface)",
    borderRadius: "var(--radius)",
    border: "1px solid var(--border)",
  },
  emptyText: { color: "var(--text-muted)", fontSize: 14 },
  group: { marginBottom: 20 },
  noFaceGroup: {
    marginBottom: 20,
    border: "1px solid var(--warning)",
    borderRadius: "var(--radius)",
    padding: 12,
    background: "rgba(251, 191, 36, 0.04)",
  },
  noFaceLabel: { color: "var(--warning)" },
  noFaceCard: {
    background: "var(--bg)",
    borderRadius: "var(--radius-sm)",
    border: "1px solid var(--warning)",
    overflow: "hidden",
    opacity: 0.8,
  },
  dismissNoFaceBtn: {
    background: "var(--warning)",
    border: "none",
    borderRadius: "var(--radius-sm)",
    color: "#000",
    fontSize: 12,
    fontWeight: 600,
    padding: "5px 14px",
    cursor: "pointer",
  },
  groupHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  collapseBtn: {
    background: "none",
    border: "none",
    color: "var(--text)",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "4px 0",
  },
  arrow: { display: "inline-block", fontSize: 10, transition: "transform 0.2s ease" },
  groupCount: { fontWeight: 400, color: "var(--text-muted)", fontSize: 13 },
  dismissBtn: {
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-sm)",
    color: "var(--text-muted)",
    fontSize: 12,
    padding: "3px 10px",
    cursor: "pointer",
  },
  scrollContainer: {
    maxHeight: 500,
    overflowY: "auto",
    borderRadius: "var(--radius)",
    border: "1px solid var(--border)",
    background: "var(--surface)",
    padding: 12,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: 10,
  },
  card: {
    background: "var(--bg)",
    borderRadius: "var(--radius-sm)",
    border: "1px solid var(--border)",
    overflow: "hidden",
    position: "relative",
  },
  cardExcluded: { opacity: 0.5 },
  dragHandle: {
    position: "absolute",
    top: 4,
    left: 4,
    width: 24,
    height: 24,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    color: "rgba(255,255,255,0.7)",
    background: "rgba(0,0,0,0.45)",
    borderRadius: 4,
    cursor: "grab",
    zIndex: 2,
    userSelect: "none",
  },
  thumbnail: { width: "100%", aspectRatio: "3/4", objectFit: "cover", display: "block" },
  noFace: {
    width: "100%",
    aspectRatio: "3/4",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(251, 191, 36, 0.08)",
    gap: 4,
  },
  noFaceIcon: { fontSize: 24, fontWeight: 700, color: "var(--warning)" },
  noFaceText: { fontSize: 12, color: "var(--warning)" },
  cardInfo: { padding: "6px 8px 2px" },
  filename: {
    fontSize: 11,
    color: "var(--text)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  date: { fontSize: 10, color: "var(--text-muted)", marginTop: 2 },
  cardActions: {
    padding: "4px 8px 8px",
    display: "flex",
    gap: 4,
    alignItems: "center",
  },
  btnSmall: {
    fontSize: 11,
    padding: "2px 7px",
    borderRadius: "var(--radius-sm)",
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    transition: "all 0.15s",
  },
  btnIncluded: { borderColor: "var(--success)", color: "var(--success)" },
  btnExcluded: { borderColor: "var(--text-muted)", color: "var(--text-muted)" },
  btnRealign: { borderColor: "var(--primary)", color: "var(--primary)" },
  btnDelete: { borderColor: "var(--danger)", color: "var(--danger)", marginLeft: "auto" },
};

export default styles;
